// templates/starters/react-typescript/src/App.tsx
import { useState } from 'react';
import styles from './App.module.css';

const PROJECT = '__PROJECT_NAME__';

export default function App() {
  const [status,   setStatus]   = useState('');
  const [response, setResponse] = useState('');
  const [ok,       setOk]       = useState(false);
  const [loading,  setLoading]  = useState(false);

  async function checkHealth() {
    setLoading(true);
    setStatus('');
    setResponse('');
    try {
      const res  = await fetch('/health');
      const data = await res.json();
      setOk(true);
      setStatus('healthy');
      setResponse(JSON.stringify(data, null, 2));
    } catch (e) {
      setOk(false);
      setStatus('unreachable');
      setResponse((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className={styles.shell}>

      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerInner}>
          <div className={styles.brand}>
            <span className={styles.brandDot} />
            <span className={styles.brandName}>Engineering OS</span>
          </div>
          <span className={styles.projectBadge}>{PROJECT}</span>
        </div>
      </header>

      {/* Main */}
      <main className={styles.main}>
        <div className={styles.content}>

          {/* Hero */}
          <section className={styles.hero}>
            <p className={styles.eyebrow}>Project</p>
            <h1 className={styles.heroTitle}>{PROJECT}</h1>
            <p className={styles.heroSub}>
              Design for evolution. Build software that survives change.
            </p>
          </section>

          {/* Health Check */}
          <section className={styles.card}>
            <div className={styles.cardHeader}>
              <span className={styles.cardLabel}>Backend Status</span>
              <span className={styles.endpoint}>GET /health</span>
            </div>
            <div className={styles.cardBody}>
              <button className={styles.btn} onClick={checkHealth} disabled={loading}>
                {loading ? <span className={styles.spinner} /> : 'Check Health'}
              </button>

              {status && (
                <div className={`${styles.result} ${ok ? styles.resultOk : styles.resultErr}`}>
                  <div className={styles.resultHeader}>
                    <span className={styles.resultStatus}>
                      {ok ? '● HEALTHY' : '● UNREACHABLE'}
                    </span>
                  </div>
                  <pre className={styles.resultBody}>{response}</pre>
                </div>
              )}
            </div>
          </section>

          {/* Stack */}
          <div className={styles.stack}>
            {[
              { label: 'Framework',    value: 'Engineering OS' },
              { label: 'Frontend',     value: 'React + Vite'   },
              { label: 'Architecture', value: 'MVVM + Clean'   },
              { label: 'Backend',      value: ':8000'          },
            ].map(({ label, value }) => (
              <div key={label} className={styles.stackItem}>
                <span className={styles.stackLabel}>{label}</span>
                <span className={styles.stackValue}>{value}</span>
              </div>
            ))}
          </div>

        </div>
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        Built with <span className={styles.footerBrand}>Engineering OS</span>
        {' · '}
        <a className={styles.footerLink} href="https://github.com/jcarrenoa" target="_blank" rel="noreferrer">
          github.com/jcarrenoa
        </a>
      </footer>

    </div>
  );
}

// templates/starters/angular-typescript/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  readonly title   = '__PROJECT_NAME__';
  readonly stack   = 'Angular';
  status   = '';
  response = '';
  ok       = false;
  loading  = false;

  constructor(private http: HttpClient) {}

  checkHealth() {
    this.loading  = true;
    this.status   = '';
    this.response = '';
    this.http.get('/health').subscribe({
      next: (data) => {
        this.ok       = true;
        this.status   = 'healthy';
        this.response = JSON.stringify(data, null, 2);
        this.loading  = false;
      },
      error: (e) => {
        this.ok       = false;
        this.status   = 'unreachable';
        this.response = e.message;
        this.loading  = false;
      },
    });
  }
}

<div class="shell">

  <!-- Header -->
  <header class="header">
    <div class="header-inner">
      <div class="brand">
        <span class="brand-dot"></span>
        <span class="brand-name">Engineering OS</span>
      </div>
      <span class="project-badge">{{ title }}</span>
    </div>
  </header>

  <!-- Main -->
  <main class="main">
    <div class="content">

      <!-- Hero -->
      <section class="hero">
        <p class="eyebrow">Project</p>
        <h1 class="hero-title">{{ title }}</h1>
        <p class="hero-sub">
          Design for evolution. Build software that survives change.
        </p>
      </section>

      <!-- Health Check -->
      <section class="card">
        <div class="card-header">
          <span class="card-label">Backend Status</span>
          <span class="endpoint">GET /health</span>
        </div>
        <div class="card-body">
          <button class="btn" (click)="checkHealth()" [disabled]="loading">
            <span *ngIf="!loading">Check Health</span>
            <span *ngIf="loading" class="spinner"></span>
          </button>

          <div *ngIf="status" class="result" [class.result--ok]="ok" [class.result--err]="!ok">
            <div class="result-header">
              <span class="result-status">{{ ok ? '● HEALTHY' : '● UNREACHABLE' }}</span>
            </div>
            <pre class="result-body">{{ response }}</pre>
          </div>
        </div>
      </section>

      <!-- Stack -->
      <div class="stack">
        <div class="stack-item">
          <span class="stack-label">Framework</span>
          <span class="stack-value">Engineering OS</span>
        </div>
        <div class="stack-item">
          <span class="stack-label">Frontend</span>
          <span class="stack-value">{{ stack }}</span>
        </div>
        <div class="stack-item">
          <span class="stack-label">Architecture</span>
          <span class="stack-value">MVVM + Clean</span>
        </div>
        <div class="stack-item">
          <span class="stack-label">Backend</span>
          <span class="stack-value">:8000</span>
        </div>
      </div>

    </div>
  </main>

  <!-- Footer -->
  <footer class="footer">
    Built with <span class="footer-brand">Engineering OS</span>
    &nbsp;·&nbsp;
    <a class="footer-link" href="https://github.com/jcarrenoa" target="_blank">github.com/jcarrenoa</a>
  </footer>

</div>
